# apt install git vim screen make
#
#

all	:
	apt install git vim screen make
	apt install rcs cvs subversion rsync
	apt install x11-repo
	apt install xorg-twm aterm
	apt install tigervnc
	apt install man texinfo
	apt install feh
	apt install irssi
	apt install tcsh zsh lynx bc busybox joe fortune
	apt install qemu-system-i386
	apt install clang
	apt install autoconf automake libtool yasm
